= A Groovy Light Table client - I'm not dead (yet)
Magnus Rundberget
2015-01-25
:jbake-type: post
:jbake-status: published
:jbake-tags: lighttable, groovy, gradle, clojurescript
:id: gr_lt_status_jan2015

== Background
In 2014 I blogged about the process of evolving a groovy(/gradle) plugin for Light Table from scratch.

.Posts so far:
* link:/blog/2014/gr_lt_part1.html[A Groovy Light Table client - Step 1: Connecting the client]
* link:/blog/2014/gr_lt_part2.html[A Groovy Light Table client - Step 2: Evaluating Code]
* link:/blog/2014/gr_lt_part3.html[A Groovy Light Table client - Step 3: Running out of quick wins]
* link:/blog/2014/gr_lt_part4.html[A Groovy Light Table client - Step 4: Exploring new avenues with Gradle]
* link:/blog/2014/gr_lt_part5.html[A Groovy Light Table client - Step 5: Gradle dependencies in Light Table with dagre-D3]

I even did a link:/blog/2014/groovy_repl.html[screen cast] showing off some of the features so far.



== So what happened ?

After the summer holidays my Open Source mojo was drained, I needed a break and I went into uphill cycling mode.


=== Light Table doubts
First of all. I haven't given up on Light Table I somehow even feel strongly obliged to hang in there longer
than most people given that I've contributed. I still use Light Table, actually more than ever because I'm currently
hacking on a clojure/clojurescript project.

In October the founder of Light Table annouced Eve and released this http://www.chris-granger.com/2014/10/01/beyond-light-table/[blog post]
Obviously there was initial fears that this would be the end of Light Table. However 3 of the most active contributors
to Light Table stepped up. There was a lot of visible activity initially (proper spring cleaning of the issues log).
However visible activity from Light Table has been in steady decline and the last release was 21. november of last year.


I believe they are working on moving from node-webkit to atom shell, the layout system is being revised. There is also a hack night planned
in a few days time.

I guess I just wished someone stepped up and outlined a clear road-map for Light Table and that
a steady stream of releases towards a version 1.0 started coming out :)


=== Possibilites for further developments
Great things are happening with gradle I believe in terms of performance and also in terms of whats possible
to achieve with the Tooling API. This opens up a whole range of oportunities to provide IDE support for languages that gradle supports.

The groovy and gradle parts of the currenty groovy plugin should probably be split with a generic gradle
plugin and specific language plugins (scala, java...) depending on that.


.How about things like ?:
* Continuous unit testing - utilizing gradle builds incremental nature and the coming watcher tasks.
Couple that with showing results inline in Light Table
* Compilation - Same story here, show compilation errors inline
* run webapp - Run apropriate gradle task to start your webapp and fire up a browser window inline in lighttable
, maybe even hook it up with a browser debug/repl connection



=== Help needed
I'd love to hear if anyone has actually used the plugin and if so which parts of it.

I'm currently fully engaged in a clojure/clojurescript project, which takes all of my day time and quite a few evenings.
It puts me in a better shape to contribute to Light Table, but currently leaves me little time to do so.

.That might change though, but I guess I need 2 things to happen before I pick up work on this plugin:
. Some visible progress from Light Table to show that it's intending to survive
. Hopefully someone feels inspired to help contribute progressing the plugin (pull requests are welcome)








